---
# Configure PGDG PostgreSQL repository

- name: Install postgresql-common package
  ansible.builtin.apt:
    name: postgresql-common
    state: present
    update_cache: yes

- name: Add PGDG repository
  ansible.builtin.shell:
    cmd: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
    creates: /etc/apt/sources.list.d/pgdg.list

- name: Create PGDG APT preferences file
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/pgdg
    content: |
      Package: *
      Pin: release o=pgdg
      Pin-Priority: 1001
    mode: '0644'
    owner: root
    group: root

- name: Check for other PGDG references in preferences.d
  ansible.builtin.find:
    paths: /etc/apt/preferences.d
    patterns: '*'
    excludes: 'pgdg'
    contains: '.*pgdg.*'
  register: other_pgdg_files

- name: Warn about other PGDG references
  ansible.builtin.debug:
    msg: "WARNING: Found PGDG reference in {{ item.path }}, please review manually"
  loop: "{{ other_pgdg_files.files }}"
  when: other_pgdg_files.matched > 0

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
