---
# System tuning for PostgreSQL

- name: Create sysctl configuration file
  ansible.builtin.template:
    src: 99-ibp.conf.j2
    dest: /etc/sysctl.d/99-ibp.conf
    mode: '0644'
    owner: root
    group: root
  register: sysctl_config

- name: Apply sysctl settings
  ansible.builtin.shell:
    cmd: sysctl -p /etc/sysctl.d/99-ibp.conf
  when: sysctl_config.changed

- name: Configure security limits
  ansible.builtin.copy:
    dest: /etc/security/limits.d/ibp.conf
    content: |
      * soft nofile 1048576
      * hard nofile 1048576
      * soft memlock unlimited
      * hard memlock unlimited
    mode: '0644'
    owner: root
    group: root

- name: Configure PAM to use limits
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "session required       pam_limits.so"
    insertafter: EOF
    state: present
  loop:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: Configure GAI (getaddrinfo)
  ansible.builtin.lineinfile:
    path: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"
    insertafter: EOF
    state: present

- name: Find netplan configuration files
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: '*.yaml,*.yml'
  register: netplan_files

- name: Backup netplan files
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ item.path }}.backup.{{ ansible_date_time.epoch }}"
    remote_src: yes
  loop: "{{ netplan_files.files }}"
  when: netplan_files.matched > 0

- name: Add link-local configuration to netplan (manual step required)
  ansible.builtin.debug:
    msg: |
      WARNING: Netplan YAML modification requires manual intervention or custom Python script
      Please add 'link-local: []' under each ethernet interface in /etc/netplan/*.yaml
      Example:
        ethernets:
          ens3:
            dhcp4: true
            link-local: []
  when: netplan_files.matched > 0
